CardEaseXMLClient-PHP: Response Class Reference
Response Class Reference
A class holding all of the data that constitutes a Response from CardEaseXML.
Public Member Functions
Response ()
Constructs a new response and initialises all variables.
getTransactionId ()
Gets the identifier for a transaction using the gateway.
getCustomerVaultId ()
Gets the Customer Vault ID associated with this request for the Omni Gateway.
getAddressResponseData ()
Gets the raw response data received from the address verification with the issuer.
getAddressResult ()
Gets the result of the address verification with the issuer.
getAuthCode ()
Gets the authorisation code found in this response.
getAuthorisationEntity ()
Gets the authorisation entity found in the response.
getCardEaseReference ()
Gets the CardEaseXML reference found in this response.
getCardHash ()
Gets the card hash found in the response that can be used to reference a card in a follow-up transaction.
getCardReference ()
Gets the card reference found in the response that can be used to reference a card in a follow-up transaction.
getCardScheme ()
Gets the description of the card scheme used in the request.
getCardTokens ()
Gets the card tokens received in the response.
getCSCResponseData ()
Gets the raw response data received from the security code verification with the issuer.
getCSCResult ()
Gets the result of the security code verification with the issuer.
getDoNotReauthorize ()
Gets whether the transaction has been declined and the issuer has indicated that the same transaction should not be reattempted with the same parameters.
getDoNotReauthorizeReason ()
Gets the reason the issuer has indicated that the same transaction should not be reattempted with the same parameters.
getDuplicate ()
Gets whether the transaction was recognised as a duplicate.
getErrors ()
Gets a list of the errors that we encountered when trying to process the request.
getExpiryDate ()
Gets the expiry date associated with the card in this response.
getExpiryDateFormat ()
Gets the expiry date format associated with the card in the response.
getExtendedProperties ()
Gets the list of extended properties found in the response.
getFallforwardToContact ()
Gets if it is needed to fallforward to contact.
getICCCertificationAuthorities ()
Gets the list of ICC certification authorities found in the response.
getICCPublicKeyClearExisting ()
Gets the indicator in the response that says whether to clear the existing public key list.
getICCPublicKeyContent ()
Gets a description of the public key list content.
getICCPublickeyReplaceExisting ()
Gets the indicator in the response that says whether to replace the existing public key list.
getICCPublicKeyType ()
Gets the type of the public key list.
getICCTags ()
Gets the list of ICC tags found in this response.
getICCType ()
Gets the type of ICC transaction associated with this response.
getIssueNumber ()
Gets the issue number associated with the card in this response.
getLocalDateTime ()
Gets the date and time at the terminal's location.
getLocalDateTimeFormat ()
Gets the local date and time format at the terminal's location.
getOnlinePinRequired ()
Gets if it is needed to online pin required.
getOriginatingIPAddressCity ()
Gets the city of the originating IP address found in this response.
getOriginatingIPAddressContinent ()
Gets the continent of the originating IP address found in this response.
getOriginatingIPAddressContinentAlpha2 ()
Gets the ISO 3166 continent alpha-2 of the originating IP address found in this response.
getOriginatingIPAddressCountry ()
Gets the country of the originating IP address found in this response.
getOriginatingIPAddressCountryAlpha2 ()
Gets the ISO 3166 country alpha-2 of the originating IP address found in this response.
getOriginatingIPAddressCountryCode ()
Gets the ISO 3166 country code of the originating IP address found in this response.
getOriginatingIPAddressIsBlackListed ()
Gets whether the originating IP address is black listed.
getOriginatingIPAddressIsKnownProxy ()
Gets whether the originating IP address is a known proxy.
getOriginatingIPAddressRegion ()
Gets the region of the originating IP address found in this response.
getOriginatingIPAddressRegionCode ()
Gets the region code of the originating IP address found in this response.
getOriginatingIPAddressZipCode ()
Gets the zip code of the originating IP address found in this response.
getPAR ()
Gets the PAR (Primary Account Reference) found in this response.
getPAN ()
Gets the masked PAN (Primary Account Number) found in this response.
getFundingCard ()
Gets the Funding Card found in this response.
getResultCode ()
Gets the result code that has been obtained from the CardEase platform when processing the source request.
getStartDate ()
Gets the start date associated with the card in this response.
getStartDateFormat ()
Gets the start date format associated with the card in this response.
getThreeDSecureRequired ()
Gets if it is 3-D Secure required.
getVoiceReferralTelephoneNumber ()
Gets the voice referral telephone number found in the response.
getUserReference ()
Gets the user reference found in this response.
getUTC ()
Gets the Coordinated Universal Time.
getUTCFormat ()
Gets the Coordinated Universal Time.
getZipCodeResponseData ()
Gets the raw response data received from the zip code/post code verification with the issuer.
getZipCodeResult ()
Gets the result of the zip code/post code verification with the issuer.
parseTransactionDetails ($responseNode)
parseResult ($responseNode)
parseCardDetails ($responseNode)
parseICCTags ($iccNode)
parseFundingCard ($fundingCardNode)
parseCardToken ($cardTokenChildNode)
parseAdditionalVerification ($responseNode)
parseICCPublicKeys ($responseNode)
parseCertificationAuthority ($certificationAuthorityNode)
parsePublicKey ($publicKeyNode, $certificationAuthority)
parseExtendedPropertyList ($node)
isNullOrEmptyString ($str)
cardTokensToString ()
toString ()
Returns a detailed string showing this response.
Public Attributes
$m_transactionId = null
The identifier for transactions using the gateway.
$m_customerVaultId = null
ID of the Customer Vault.
Detailed Description
A class holding all of the data that constitutes a Response from CardEaseXML.
The necessary components of the request should be retrieved (using the 'getters'). The response can only be obtained from the Client in response to a Request.
Author
Creditcall Ltd
See also
Client
Request
Member Function Documentation
cardTokensToString()
Response::cardTokensToString ()
Referenced by toString().
getAddressResponseData()
Response::getAddressResponseData ()
Gets the raw response data received from the address verification with the issuer.
The content of this is dependant upon the acquirer, country, protocol etc. This is an alphanumeric string. This will be available if required in the original request.
Returns
string The raw response data received from the address verfication. This will be null if no raw address data was found in this response.
getAddressResult()
Response::getAddressResult ()
Gets the result of the address verification with the issuer.
This will be available if required in the original request.
Returns
string The result of the address verification:
NotChecked The address was not checked against the issuer records
NotMatched The address did not match issuer records
Matched The address matched issuer records
PartialMatch The address partially matched issuer records
This will be null if no result data was found in the response.
getAuthCode()
Response::getAuthCode ()
Gets the authorisation code found in this response.
This will only be present if the transaction was approved. This is an alphanumeric string with a maximum length of 12 characters.
Returns
string The authorisation code found in this response. This will be null if no authorisation code was found in this response.
getAuthorisationEntity()
Response::getAuthorisationEntity ()
Gets the authorisation entity found in the response.
Returns
string The authorisation entity found in the response. This will be null if no authorisation entity was found in the response.
getCardEaseReference()
Response::getCardEaseReference ()
Gets the CardEaseXML reference found in this response.
This is a unique reference that can be used with CardEaseXML during follow-up requests related to the original such as confirmations, refunds and voids. This is an alphanumeric string with a fixed length of 36 characters.
Returns
string The CardEaseXML reference found in this response. This will be null if no CardEase reference was found in this response.
getCardHash()
Response::getCardHash ()
Gets the card hash found in the response that can be used to reference a card in a follow-up transaction.
This is an alphanumeric string with a fixed length of 28 characters. Used in conjunction with the CardReference property. The benefit of being able to reference a previously used card is that an integrator need not store actual card details on their system for repeat transactions. This reduces the risk of card information being compromised, and reduces the integrators PCI requirements.
Returns
string The card hash found in the response that can be used to reference a card in a follow-up transaction.
See also
getCardReference()
getCardReference()
Response::getCardReference ()
Gets the card reference found in the response that can be used to reference a card in a follow-up transaction.
This is an alphanumeric string with a fixed length of 36 characters. Used in conjunction with the CardHash property. The benefit of being able to reference a previously used card is that an integrator need not store actual card details on their system for repeat transactions. This reduces the risk of card information being compromised, and reduces the integrators PCI requirements.
Returns
string The card reference found in the response that can be used to reference a card in a follow-up transaction.
See also
getCardHash()
getCardScheme()
Response::getCardScheme ()
Gets the description of the card scheme used in the request.
This can be used on a receipt. This is an alphanumeric string with a maximum length of 50 characters.
Returns
string The description of the card scheme used in the request. This will be null if no card scheme was found in this response.
getCardTokens()
Response::getCardTokens ()
Gets the card tokens received in the response.
Returns
array The card tokens received in the response. This will be null if no card tokens were not found in this response.
getCSCResponseData()
Response::getCSCResponseData ()
Gets the raw response data received from the security code verification with the issuer.
This is also referred to as CVV, CVC and CV2. The content of this is dependant upon the acquirer, country, protocol etc. This is an alphanumeric string. This will be available if required in the original request. If the CSC validation fails the authorisation may be automatically declined or may continue to be approved. If the authorisation is approved the CSC result should be checked.
Returns
string The raw response data received from the security code verfication. This will be null if no raw security code data was found in this response.
getCSCResult()
Response::getCSCResult ()
Gets the result of the security code verification with the issuer.
This will be available if required in the original request. If the CSC validation fails the authorisation may be automatically declined or may continue to be approved. If the authorisation is approved the CSC result should be checked.
Returns
string The result of the security code verification:
NotChecked The security code was not checked against the issuer records
NotMatched The security code did not match the issuer records
Matched The security code matched the issuer records
This will be null if no result data was found in the response.
getCustomerVaultId()
Response::getCustomerVaultId ()
Gets the Customer Vault ID associated with this request for the Omni Gateway.
If the Customer Vault Command is add-customer this is optional, if the Customer Vault ID is not supplied it will be generated. If the Customer Vault Command is update-customer then this field is mandatory. The value must be one that was previously used with an add-customer Customer Vault Command.
Returns
string Customer Vault ID associated with this request.
References $m_customerVaultId.
getDoNotReauthorize()
Response::getDoNotReauthorize ()
Gets whether the transaction has been declined and the issuer has indicated that the same transaction should not be reattempted with the same parameters.
Returns
bool Whether the transaction has been declined and the issuer has indicated that the same transaction should not be reattempted with the same parameters.
getDoNotReauthorizeReason()
Response::getDoNotReauthorizeReason ()
Gets the reason the issuer has indicated that the same transaction should not be reattempted with the same parameters.
Returns
String The reason the issuer has indicated that the same transaction should not be reattempted with the same parameters.
getDuplicate()
Response::getDuplicate ()
Gets whether the transaction was recognised as a duplicate.
Returns
bool Whether the transaction was recognised as a duplicate.
getErrors()
Response::getErrors ()
Gets a list of the errors that we encountered when trying to process the request.
Each error contains an error code and an error message.
Returns
array A list of the errors that we encountered when trying to process the request. This will be empty if no errors were found in the response.
See also
CexmlError
getExpiryDate()
Response::getExpiryDate ()
Gets the expiry date associated with the card in this response.
This will match the expiry date format. This is a character string with a maximum length of 10 characters.
Returns
string The expiry date associated with the card in this response. This will be null if no expiry date was found in this response.
See also
getExpiryDateFormat()
getExpiryDateFormat()
Response::getExpiryDateFormat ()
Gets the expiry date format associated with the card in the response.
This will match the format of the expiry date and can include separators such as - and /. This is a character string with a maximum length of 10 characters. The available options are shown in the following table:
Format Description Example
yyyy Year with century 2004
yy Year without century 04
MM Month of year 01
dd Day of month 27
Returns
string The expiry date format associated with the card in this response. This will be null if no expiry date format was found in the response.
See also
getExpiryDate()
getExtendedProperties()
Response::getExtendedProperties ()
Gets the list of extended properties found in the response.
Returns
array The list of extended properties found in the response. This will be null if no extended properties were found in the response.
getFallforwardToContact()
Response::getFallforwardToContact ()
Gets if it is needed to fallforward to contact.
Returns
boolean The boolean value of fallforward to contact This will be false if fallforward to contact is not found in the response.
getFundingCard()
Response::getFundingCard ()
Gets the Funding Card found in this response.
Returns
FundingCard The Funding Card found in this response.
getICCCertificationAuthorities()
Response::getICCCertificationAuthorities ()
Gets the list of ICC certification authorities found in the response.
Returns
array The list of certification authorities found in the response. This will be null if no certification authorities were found in the response.
getICCPublicKeyClearExisting()
Response::getICCPublicKeyClearExisting ()
Gets the indicator in the response that says whether to clear the existing public key list.
Returns
bool The indicator in the response that says whether to clear the existing public key list. This will be null if no indicator was found.
See also
getICCPublickeyReplaceExisting()
getICCPublicKeyContent()
Response::getICCPublicKeyContent ()
Gets a description of the public key list content.
For example 'complete'. It is an alphanumeric string.
Returns
string A description of the public key list content. This will be null if no description was found.
See also
getICCPublicKeyType()
getICCPublickeyReplaceExisting()
Response::getICCPublickeyReplaceExisting ()
Gets the indicator in the response that says whether to replace the existing public key list.
Returns
bool The indicator in the response that says whether to replace the existing public key list. This will be null if no indicator was found.
See also
getICCPublicKeyClearExisting()
getICCPublicKeyType()
Response::getICCPublicKeyType ()
Gets the type of the public key list.
For example 'EMV'. It is an alphanumeric string.
Returns
string The type of the public key list. This will be null if no type was found.
See also
getICCPublicKeyContent()
getICCTags()
Response::getICCTags ()
Gets the list of ICC tags found in this response.
Each ICC tag has an id, type and value. For example, a tag of 0x9f02/AsciiHex/000000000100 is using to specify the transaction amount. These are mandatory for an EMV transaction.
Returns
array The list of ICC tags found in this response. This will be null if no ICC tags were found in this response.
See also
ICCTag
getICCType()
Response::getICCType ()
Gets the type of ICC transaction associated with this response.
This is an alphanumeric string. This is mandatory for ICC authorisations and by default is 'EMV'. An EMV transaction must have associated ICC tags.
Returns
string The type of ICC transaction associated with the request. This will be null if no ICC type was found in this response.
See also
ICCTag
getICCTags()
getIssueNumber()
Response::getIssueNumber ()
Gets the issue number associated with the card in this response.
This is dependant upon the card scheme associated with the card and will be exactly as found on the card (including any leading 0's). This is a numeric string with a maximum length of 2 characters.
Returns
string The issue number associated with the card in this response. This will be null if no issue number was found in this response.
getLocalDateTime()
Response::getLocalDateTime ()
Gets the date and time at the terminal's location.
This can be used on a receipt and will match the local date and time format. This is a character string.
Returns
string The date and time at the terminal's location. This will be null if no local date and time was found in this response.
See also
getLocalDateTimeFormat()
getLocalDateTimeFormat()
Response::getLocalDateTimeFormat ()
Gets the local date and time format at the terminal's location.
This will match the format of the local date and time and can include separators such as :, - and /. This is a character string. The available options are shown in the following table:
Format Description Example
yyyy Year with century 2004
yy Year without century 04
MM Month of year 01
dd Day of month 27
HH Hour of day (24 hour) 17
mm Minute of hour 53
ss Second of minute 43
Returns
string The local date and time format at the terminal's location. This will be null if no local date and time format was found in the response.
See also
getLocalDateTime()
getOnlinePinRequired()
Response::getOnlinePinRequired ()
Gets if it is needed to online pin required.
Returns
boolean The boolean value of online pin required. This will be false if online pin required is not found in the response.
getOriginatingIPAddressCity()
Response::getOriginatingIPAddressCity ()
Gets the city of the originating IP address found in this response.
Returns
string The city of the originating IP address found in this response. This will be null if no city was found in this response.
getOriginatingIPAddressContinent()
Response::getOriginatingIPAddressContinent ()
Gets the continent of the originating IP address found in this response.
Returns
string The continent of the originating IP address found in this response. This will be null if no continent was found in this response.
getOriginatingIPAddressContinentAlpha2()
Response::getOriginatingIPAddressContinentAlpha2 ()
Gets the ISO 3166 continent alpha-2 of the originating IP address found in this response.
Returns
string The ISO 3166 continent alpha-2 of the originating IP address found in this response. This will be null if no ISO 3166 continent alpha-2 was found in this response.
getOriginatingIPAddressCountry()
Response::getOriginatingIPAddressCountry ()
Gets the country of the originating IP address found in this response.
Returns
string The country of the originating IP address found in this response. This will be null if no country was found in this response.
getOriginatingIPAddressCountryAlpha2()
Response::getOriginatingIPAddressCountryAlpha2 ()
Gets the ISO 3166 country alpha-2 of the originating IP address found in this response.
Returns
string The ISO 3166 country alpha-2 of the originating IP address found in this response. This will be null if no ISO 3166 country alpha-2 was found in this response.
getOriginatingIPAddressCountryCode()
Response::getOriginatingIPAddressCountryCode ()
Gets the ISO 3166 country code of the originating IP address found in this response.
Returns
string The ISO 3166 country code of the originating IP address found in this response. This will be null if no ISO 3166 country code was found in this response.
getOriginatingIPAddressIsBlackListed()
Response::getOriginatingIPAddressIsBlackListed ()
Gets whether the originating IP address is black listed.
Returns
bool Whether the originating IP address is black listed. This will be false if this was not found in the response.
getOriginatingIPAddressIsKnownProxy()
Response::getOriginatingIPAddressIsKnownProxy ()
Gets whether the originating IP address is a known proxy.
Returns
bool Whether the originating IP address is a known proxy. This will be false if this was not found in the response.
getOriginatingIPAddressRegion()
Response::getOriginatingIPAddressRegion ()
Gets the region of the originating IP address found in this response.
Returns
string The region of the originating IP address found in this response. This will be null if no region was found in this response.
getOriginatingIPAddressRegionCode()
Response::getOriginatingIPAddressRegionCode ()
Gets the region code of the originating IP address found in this response.
Returns
string The region code of the originating IP address found in this response. This will be null if no region code was found in this response.
getOriginatingIPAddressZipCode()
Response::getOriginatingIPAddressZipCode ()
Gets the zip code of the originating IP address found in this response.
Returns
string The zip code of the originating IP address found in this response. This will be null if no zip code was found in this response.
getPAN()
Response::getPAN ()
Gets the masked PAN (Primary Account Number) found in this response.
The PAN is masked with x's for security. This is an alphanumeric string with a minimum length of 12 characters and a maximum length of 19 characters.
Returns
string The PAN (Primary Account Number) found in this response. This will be null if no PAN was found in this response.
getPAR()
Response::getPAR ()
Gets the PAR (Primary Account Reference) found in this response.
Returns
string The PAR (Primary Account Reference) found in the response. This will be null if no PAR was found in the response. This is an alphanumeric string with a length of 29 characters.
getResultCode()
Response::getResultCode ()
Gets the result code that has been obtained from the CardEase platform when processing the source request.
Returns
string The result code that has been obtained from the CardEase platform when processing the source request. This will be null if no result code was found in this response.
getStartDate()
Response::getStartDate ()
Gets the start date associated with the card in this response.
This will match the start date format. This is a character string with a maximum length of 10 characters.
Returns
string The start date associated with the card in this response. This will be null if no start date was found in this response.
See also
getStartDateFormat()
getStartDateFormat()
Response::getStartDateFormat ()
Gets the start date format associated with the card in this response.
This will match the format of the start date and can include separators such as - and /. This is a character string with a maximum length of 10 characters. The available options are shown in the following table:
Format Description Example
yyyy Year with century 2004
yy Year without century 04
MM Month of year 01
dd Day of month 27
Returns
string The start date format associated with the card in this response. This will be null if no start date format was found in the response.
See also
getStartDate()
getThreeDSecureRequired()
Response::getThreeDSecureRequired ()
Gets if it is 3-D Secure required.
Returns
boolean Gets if in the response to an authorisation request the issuer has indicated that 3-D Secure authentication is required
This will be false if the issuer has indicated that 3-D Secure authentication is not required in the authorisation response.
getTransactionId()
Response::getTransactionId ()
Gets the identifier for a transaction using the gateway.
Returns
string The identifier for a transaction that uses the gateway. This will be null if the gateway is not used.
References $m_transactionId.
getUserReference()
Response::getUserReference ()
Gets the user reference found in this response.
This will be the same as that in the original request. This allows a user to attached their own reference against a request and verify it against this response. This is an alphanumeric string with a maximum length of 50 characters. Use of the user reference is optional for all requests.
Returns
string The user reference found in this response. This will be null if no user reference was found in this response.
getUTC()
Response::getUTC ()
Gets the Coordinated Universal Time.
This is a character string.
Returns
string The Coordinated Universal Time. This will be null if no UTC was found in this response.
See also
getLocalDateTimeFormat()
getUTCFormat()
Response::getUTCFormat ()
Gets the Coordinated Universal Time.
This will match the format of the UTC and can include separators such as :, - and /. This is a character string. The available options are shown in the following table:
Format Description Example
yyyy Year with century 2004
yy Year without century 04
MM Month of year 01
dd Day of month 27
HH Hour of day (24 hour) 17
mm Minute of hour 53
ss Second of minute 43
Returns
string The Coordinated Universal Time. This will be null if no UTC was found in the response.
See also
getUTC()
getVoiceReferralTelephoneNumber()
Response::getVoiceReferralTelephoneNumber ()
Gets the voice referral telephone number found in the response.
Returns
string The voice referral telephone number found in the response.
getZipCodeResponseData()
Response::getZipCodeResponseData ()
Gets the raw response data received from the zip code/post code verification with the issuer.
The content of this is dependant upon the acquirer, country, protocol etc. This is an alphanumeric string. This will be available if required in the original request.
Returns
string The raw response data received from the zip code/post code verfication. This will be null if no raw zip code/post code data was found in this response.
getZipCodeResult()
Response::getZipCodeResult ()
Gets the result of the zip code/post code verification with the issuer.
This will be available if required in the original request.
Returns
string The result of the zip code/post code verification:
NotChecked The zip code/post code was not checked against the issuer records
NotMatched The zip code/post code did not match issuer records
Matched The zip code/post code matched issuer records
PartialMatch The zip code/post code partially matched issuer records
This will be null if no result data was found in the response.
isNullOrEmptyString()
Response::isNullOrEmptyString ($str)
Referenced by parseCardToken(), and parseFundingCard().
parseAdditionalVerification()
Response::parseAdditionalVerification ($responseNode)
parseCardDetails()
Response::parseCardDetails ($responseNode)
References parseCardToken(), parseFundingCard(), and parseICCTags().
parseCardToken()
Response::parseCardToken ($cardTokenChildNode)
References isNullOrEmptyString().
Referenced by parseCardDetails(), and parseFundingCard().
parseCertificationAuthority()
Response::parseCertificationAuthority ($certificationAuthorityNode)
References parsePublicKey().
Referenced by parseICCPublicKeys().
parseExtendedPropertyList()
Response::parseExtendedPropertyList ($node)
Referenced by parseTransactionDetails().
parseFundingCard()
Response::parseFundingCard ($fundingCardNode)
References isNullOrEmptyString(), and parseCardToken().
Referenced by parseCardDetails().
parseICCPublicKeys()
Response::parseICCPublicKeys ($responseNode)
References parseCertificationAuthority().
parseICCTags()
Response::parseICCTags ($iccNode)
Referenced by parseCardDetails().
parsePublicKey()
Response::parsePublicKey ($publicKeyNode, $certificationAuthority)
Referenced by parseCertificationAuthority().
parseResult()
Response::parseResult ($responseNode)
parseTransactionDetails()
Response::parseTransactionDetails ($responseNode)
References parseExtendedPropertyList().
Response()
Response::Response ()
Constructs a new response and initialises all variables.
References ResultCode_Empty, and VerificationResult_Empty.
toString()
Response::toString ()
Returns a detailed string showing this response.
Returns
string A detailed string showing this response.
References cardTokensToString().
Member Data Documentation
$m_customerVaultId
Response::$m_customerVaultId = null
ID of the Customer Vault.
Referenced by getCustomerVaultId().
$m_transactionId
Response::$m_transactionId = null
The identifier for transactions using the gateway.
Referenced by getTransactionId().