CardEaseXMLClient-PHP: Parameters Class Reference
Parameters Class Reference
Public Member Functions
add ($key, $value)
Adds the value with the specified key.
remove ($key)
Removes the value with the specified key.
count ()
The number of items held.
isEmpty ()
Determines whether the Parameters contains any items.
containsKey ($key)
Determines whether the Parameters contains the specified key.
getValue ($key)
Public Attributes
$internalMap = array()
Member Function Documentation
add()
Parameters::add ($key, $value)
Adds the value with the specified key.
Parameters
key Key.
value Value.
containsKey()
Parameters::containsKey ($key)
Determines whether the Parameters contains the specified key.
Parameters
key Key value
Returns
true if the key is held within the data structure.
Referenced by getValue().
count()
Parameters::count ()
The number of items held.
Returns
size of the data structure.
Referenced by isEmpty().
getValue()
Parameters::getValue ($key)
Gets the value associated with the specified key.ParameterKeys for possible key values.
Parameters
key value
Returns
string of the value if contained within Parameters, else null.
References containsKey().
isEmpty()
Parameters::isEmpty ()
Determines whether the Parameters contains any items.
Returns
true if empty.
References count().
remove()
Parameters::remove ($key)
Removes the value with the specified key.
Parameters
key Key.
Member Data Documentation
$internalMap
Parameters::$internalMap = array()