CardEaseXMLClient-PHP: Client Class Reference
Client Class Reference
This class is used to process requests by sending them to CardEaseXML servers.
Public Member Functions
Client ()
Constructs a Client and initialises variables.
addServerURL ($serverURL)
Adds a CardEaseXML server URL to the list used for communication.
getServerURLs ()
Gets the list of CaseEaseXML server URLs which will be used used for communication.
getProxyHost ()
Gets the proxy host required to connect to the CardEaseXML server URLs.
getProxyPassword ()
Gets the proxy password required to connect to the CardEaseXML server URLs.
getProxyPort ()
Gets the proxy port required to connect to the CardEaseXML server URLs.
getProxyUserName ()
Gets the proxy username required to connect to the CardEaseXML server URLs.
getRequest ()
Gets the request currently associated with the CardEaseXML client.
getResponse ()
Gets the response last obtained from the CardEaseXML server.
getXMLEncoding ()
Gets the XML encoding used to communicate with the CardEaseXML server.
processRequest ()
This method uses all of the internal settings to process a CardEaseXML request.
initCurlSession (ServerURL $url, $requestXml)
setServerURLs ($serverURLs)
Sets the list of CardEaseXML server URLs to process.
setProxyHost ($proxyHost)
Sets the proxy host required to connect to the CardEaseXML server URLs.
setProxyPassword ($proxyPassword)
Sets the proxy password required to connect to the CardEaseXML server URLs.
setProxyPort ($proxyPort)
Sets the proxy port required to connect to the CardEaseXML server URLs.
setProxySettings ($proxyHost, $proxyPort, $proxyUserName, $proxyPassword)
Sets proxy settings required to connect to any of the CardEaseXML server URLs.
setProxyUserName ($proxyUserName)
Sets the proxy username required to connect to the CardEaseXML server URLs.
setRequest ($request)
Sets the request which will be used when communicating with the CardEaseXML server URLs.
setXMLEncoding ($xmlEncoding)
Sets the XML encoding which will be used when communicating with the CardEaseXML server URLs.
Static Public Member Functions
static getCardEaseXMLSDKName ()
Gets the internal name of this CardEaseXML SDK.
static getCardEaseXMLSDKVersion ()
Gets the internal version of this CardEaseXML SDK.
Detailed Description
This class is used to process requests by sending them to CardEaseXML servers.
This client supports PHP 4.x and 5.x.
To use the Client a Request object should be created and populated with the necessary transaction information such as the request type and terminal id, as well as any optional information that is required such as a user reference or address verification information.
Due to the redundancy available in the CardEase platform, the client can communicate with any number of CardEaseXML servers until a successful connection is made. Therefore, it is necessary to specify the ServerURLs with which you would like the client to communicate with in the order that you would like the communication to occur. Each of the servers will be contacted in turn until a successful request is made.
If a connection is successful processing stops and the Response can be retrieved. If a connection is unsuccessful the next host is tried until there are no more available. If the Client runs out of servers to contact, the request fails.
A successful request will obtain a Response object from the CardEase platform. The response should be examined for error information and the results of the specified transaction.
Author
Creditcall Ltd
See also
Request
Response
ServerURL
Member Function Documentation
addServerURL()
Client::addServerURL ($serverURL)
Adds a CardEaseXML server URL to the list used for communication.
During processing of a request each of these are used in turn until communication is successful.
Parameters
serverURL The server URL to add to the end of the server URL list. This should not be null. For convenience this can also be specified as a url/timeout pair rather than as a ServerURL. For example: addServerURL($url, $timeout) or addServerURL($serverURL).
See also
getServerURLs()
setServerURLs()
Client()
Client::Client ()
Constructs a Client and initialises variables.
References XMLEncoding_UTF_8.
getCardEaseXMLSDKName()
static Client::getCardEaseXMLSDKName () static
Gets the internal name of this CardEaseXML SDK.
Returns
string The name of this CardEaseXML SDK. This will not be null.
getCardEaseXMLSDKVersion()
static Client::getCardEaseXMLSDKVersion () static
Gets the internal version of this CardEaseXML SDK.
Returns
string The version of this CardEaseXML SDK. This will not be null.
getProxyHost()
Client::getProxyHost ()
Gets the proxy host required to connect to the CardEaseXML server URLs.
This must be specified in order for a proxy to be used.
Returns
string The proxy host required to connect to the CardEaseXML server URLs. If null is returned no proxy host has been specified.
See also
setProxyHost()
getProxyPassword()
Client::getProxyPassword ()
Gets the proxy password required to connect to the CardEaseXML server URLs.
The proxy password will only be used if the proxy username and proxy host are also specified.
Returns
string The proxy password required to connect to the CardEaseXML server URLs. If null is returned no proxy password has been specified.
See also
setProxyPassword()
getProxyPort()
Client::getProxyPort ()
Gets the proxy port required to connect to the CardEaseXML server URLs.
The default is port 80.
Returns
string The proxy port required to connect to the CardEaseXML server URLs.
See also
setProxyPort()
getProxyUserName()
Client::getProxyUserName ()
Gets the proxy username required to connect to the CardEaseXML server URLs.
The proxy username will only be used if the proxy password and proxy host are also specified.
Returns
string The proxy username required to connect to the CardEaseXML server URLs. If null is returned no proxy username has been specified.
See also
setProxyUserName()
getRequest()
Client::getRequest ()
Gets the request currently associated with the CardEaseXML client.
Returns
Request The request currently associated with the CardEaseXML client. If null is returned no request has been specified.
See also
setRequest()
getResponse()
Client::getResponse ()
Gets the response last obtained from the CardEaseXML server.
Returns
Response The response last obtained from the CardEaseXML server. If null is returned the request has not been sent or the communication has not been successful.
getServerURLs()
Client::getServerURLs ()
Gets the list of CaseEaseXML server URLs which will be used used for communication.
During processing of a request each of these are used in turn until communication is successful.
Returns
array The list of CardEaseXML server URLs which will be used for communication. If null is returned no ServerURLs have been specified.
See also
addServerURL()
setServerURLs()
getXMLEncoding()
Client::getXMLEncoding ()
Gets the XML encoding used to communicate with the CardEaseXML server.
By default this is 'UTF-8' (XMLEncoding.UTF_8).
Returns
string The XML encoding used to communicate with the CardEaseXML server. If null is returned XML encoding has not been specified.
initCurlSession()
Client::initCurlSession (ServerURL $url, $requestXml)
References ServerURL\getTimeout(), and ServerURL\getURL().
Referenced by processRequest().
processRequest()
Client::processRequest ()
This method uses all of the internal settings to process a CardEaseXML request.
A request and server URL must be set before processing can begin.
In turn each of the CardEaseXML server URLs are connected to and the transaction is attempted. If a communication error occurs the next server URL is used and so on. This continues until the list of server URLs is exhausted. If communication totally fails a error is thrown detailing the last connection failure.
If a proxy host has been set this communication is attempted through a proxy with the optional proxy username and password.
This method has an optional argument of the request.
Exceptions
E_USER_ERROR There was a problem with communication.
E_USER_ERROR There was a problem with the request.
E_USER_ERROR There was a problem with the response.
Returns
Response The CardEaseXML response.
References initCurlSession().
setProxyHost()
Client::setProxyHost ($proxyHost)
Sets the proxy host required to connect to the CardEaseXML server URLs.
This must be specified in order for a proxy to be used.
Parameters
proxyHost The proxy host required to connect to the CardEaseXML server URLs. If null is specified the proxy host is removed.
See also
getProxyHost()
setProxyPort()
setProxySettings()
setProxyPassword()
Client::setProxyPassword ($proxyPassword)
Sets the proxy password required to connect to the CardEaseXML server URLs.
The proxy password will only be used if the proxy username and proxy host are also specified.
Parameters
proxyPassword The proxy password required to connect to the CardEaseXML server URLs. If null is specified the proxy password is removed.
See also
getProxyPassword()
setProxyUserName()
setProxySettings()
setProxyPort()
Client::setProxyPort ($proxyPort)
Sets the proxy port required to connect to the CardEaseXML server URLs.
The default is port 80.
Parameters
proxyPort The proxy port required to connect to the CardEaseXML server URLs.
See also
getProxyPort()
setProxyHost()
setProxySettings()
setProxySettings()
Client::setProxySettings ($proxyHost, $proxyPort, $proxyUserName, $proxyPassword)
Sets proxy settings required to connect to any of the CardEaseXML server URLs.
By default the port number is 80.
Parameters
proxyHost The hostname of the proxy. If null is specified the proxy host is removed.
proxyPort The port number of the proxy.
proxyUserName The username of the proxy. If null is specified the proxy username is removed.
proxyPassword The password of the proxy. If null is specified the proxy password is removed.
See also
setProxyHost()
setProxyPort()
setProxyUserName()
setProxyPassword()
setProxyUserName()
Client::setProxyUserName ($proxyUserName)
Sets the proxy username required to connect to the CardEaseXML server URLs.
The proxy username will only be used if the proxy password and proxy host are also specified.
Parameters
proxyUserName The proxy username required to connect to the CardEaseXML server URLs. If null is specified the proxy username is removed.
See also
getProxyUserName()
setProxyUserName()
setProxySettings()
setRequest()
Client::setRequest ($request)
Sets the request which will be used when communicating with the CardEaseXML server URLs.
Parameters
request The request which wil be used when communication with the CardEaseXML server URLs. If null is specified the request is removed.
See also
getRequest()
setServerURLs()
Client::setServerURLs ($serverURLs)
Sets the list of CardEaseXML server URLs to process.
During processing of a request each of these are used in turn until communication is successful.
Parameters
serverURLs The list of CardEaseXML server URLs to process. If null is specified the list of URLs is removed.
See also
addServerURL()
getServerURLs()
setXMLEncoding()
Client::setXMLEncoding ($xmlEncoding)
Sets the XML encoding which will be used when communicating with the CardEaseXML server URLs.
Parameters
xmlEncoding The XML encoding which will be used when communicating with the CardEaseXML server URLs. If null is specified the XML encoding specification is removed.
See also
getXMLEncoding()